### PR TITLE
Correct the year name of Simula language

### PR DESCRIPTION
**Pull request by yashpalgoyal1304**
Destination: https://intersysconsulting.github.io/scala-essentials-nanodegree/docs/module1.html
Found via: ddgo 🔍 [scala vs simula](https://duckduckgo.com/?q=scala+vs+simula&t=vivaldi&ia=web)

### CODE REVIEW

**Comment by yashpalgoyal1304** [comment]
pinging for response @RHDZMOTA @oscarvarto

**Review by oscarvarto — APPROVED** [review]
LGTM

**Comment by oscarvarto** [comment]
@yashpalgoyal1304 I may no longer have write access to this repository as I no longer work for that company.

**Comment by yashpalgoyal1304** [comment]
ping @Rafailong

**Pull request closed without merging**
